### ISSUE TITLE
Compile Error on Ubuntu 16.04

### ISSUE THREAD

**Issue by tjosm** [reddcoin-project/reddcoin-3.10#127]
I'm trying to compile on Ubuntu 16.04 machine and ran into this error. Any help will be appreciated.

```
CXX      scrypt.o
scrypt.cpp: In function ‘void scrypt_1024_1_1_256_sp_sse2(const char*, char*, char*)’:
scrypt.cpp:377:50: warning: SSE vector return without SSE enabled changes the ABI [-Wpsabi]
    X.i128[k] = _mm_xor_si128(X.i128[k], V[j + k]);
                                                  ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h: In function ‘void xor_salsa8_sse2(__m128i*, const __m128i*)’:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1286:1: error: inlining failed in call to always_inline ‘__m128i _mm_xor_si128(__m128i, __m128i)’: target specific option mismatch
 _mm_xor_si128 (__m128i __A, __m128i __B)
 ^
scrypt.cpp:300:27: error: called from here
  X3 = B[3] = _mm_xor_si128(B[3], Bx[3]);
                           ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1286:1: error: inlining failed in call to always_inline ‘__m128i _mm_xor_si128(__m128i, __m128i)’: target specific option mismatch
 _mm_xor_si128 (__m128i __A, __m128i __B)
 ^
scrypt.cpp:299:27: error: called from here
  X2 = B[2] = _mm_xor_si128(B[2], Bx[2]);
                           ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1286:1: error: inlining failed in call to always_inline ‘__m128i _mm_xor_si128(__m128i, __m128i)’: target specific option mismatch
 _mm_xor_si128 (__m128i __A, __m128i __B)
 ^
scrypt.cpp:298:27: error: called from here
  X1 = B[1] = _mm_xor_si128(B[1], Bx[1]);
                           ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1286:1: error: inlining failed in call to always_inline ‘__m128i _mm_xor_si128(__m128i, __m128i)’: target specific option mismatch
 _mm_xor_si128 (__m128i __A, __m128i __B)
 ^
scrypt.cpp:297:27: error: called from here
  X0 = B[0] = _mm_xor_si128(B[0], Bx[0]);
                           ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1415:1: error: inlining failed in call to always_inline ‘__m128i _mm_shuffle_epi32(__m128i, int)’: target specific option mismatch
 _mm_shuffle_epi32 (__m128i __A, const int __mask)
 ^
scrypt.cpp:339:35: error: called from here
   X3 = _mm_shuffle_epi32(X3, 0x93);
                                   ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1415:1: error: inlining failed in call to always_inline ‘__m128i _mm_shuffle_epi32(__m128i, int)’: target specific option mismatch
 _mm_shuffle_epi32 (__m128i __A, const int __mask)
 ^
scrypt.cpp:338:35: error: called from here
   X2 = _mm_shuffle_epi32(X2, 0x4E);
                                   ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1415:1: error: inlining failed in call to always_inline ‘__m128i _mm_shuffle_epi32(__m128i, int)’: target specific option mismatch
 _mm_shuffle_epi32 (__m128i __A, const int __mask)
 ^
scrypt.cpp:337:35: error: called from here
   X1 = _mm_shuffle_epi32(X1, 0x39);
                                   ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1286:1: error: inlining failed in call to always_inline ‘__m128i _mm_xor_si128(__m128i, __m128i)’: target specific option mismatch
 _mm_xor_si128 (__m128i __A, __m128i __B)
 ^
scrypt.cpp:334:48: error: called from here
   X0 = _mm_xor_si128(X0, _mm_srli_epi32(T, 14));
                                                ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1208:1: error: inlining failed in call to always_inline ‘__m128i _mm_srli_epi32(__m128i, int)’: target specific option mismatch
 _mm_srli_epi32 (__m128i __A, int __B)
 ^
scrypt.cpp:334:21: error: called from here
   X0 = _mm_xor_si128(X0, _mm_srli_epi32(T, 14));
                     ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1286:1: error: inlining failed in call to always_inline ‘__m128i _mm_xor_si128(__m128i, __m128i)’: target specific option mismatch
 _mm_xor_si128 (__m128i __A, __m128i __B)
 ^
scrypt.cpp:333:48: error: called from here
   X0 = _mm_xor_si128(X0, _mm_slli_epi32(T, 18));
                                                ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1143:1: error: inlining failed in call to always_inline ‘__m128i _mm_slli_epi32(__m128i, int)’: target specific option mismatch
 _mm_slli_epi32 (__m128i __A, int __B)
 ^
scrypt.cpp:333:21: error: called from here
   X0 = _mm_xor_si128(X0, _mm_slli_epi32(T, 18));
                     ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1023:1: error: inlining failed in call to always_inline ‘__m128i _mm_add_epi32(__m128i, __m128i)’: target specific option mismatch
 _mm_add_epi32 (__m128i __A, __m128i __B)
 ^
scrypt.cpp:332:28: error: called from here
   T = _mm_add_epi32(X1, X2);
                            ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1286:1: error: inlining failed in call to always_inline ‘__m128i _mm_xor_si128(__m128i, __m128i)’: target specific option mismatch
 _mm_xor_si128 (__m128i __A, __m128i __B)
 ^
scrypt.cpp:331:48: error: called from here
   X1 = _mm_xor_si128(X1, _mm_srli_epi32(T, 19));
                                                ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1208:1: error: inlining failed in call to always_inline ‘__m128i _mm_srli_epi32(__m128i, int)’: target specific option mismatch
 _mm_srli_epi32 (__m128i __A, int __B)
 ^
scrypt.cpp:331:21: error: called from here
   X1 = _mm_xor_si128(X1, _mm_srli_epi32(T, 19));
                     ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1286:1: error: inlining failed in call to always_inline ‘__m128i _mm_xor_si128(__m128i, __m128i)’: target specific option mismatch
 _mm_xor_si128 (__m128i __A, __m128i __B)
 ^
scrypt.cpp:330:48: error: called from here
   X1 = _mm_xor_si128(X1, _mm_slli_epi32(T, 13));
                                                ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1143:1: error: inlining failed in call to always_inline ‘__m128i _mm_slli_epi32(__m128i, int)’: target specific option mismatch
 _mm_slli_epi32 (__m128i __A, int __B)
 ^
scrypt.cpp:330:21: error: called from here
   X1 = _mm_xor_si128(X1, _mm_slli_epi32(T, 13));
                     ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1023:1: error: inlining failed in call to always_inline ‘__m128i _mm_add_epi32(__m128i, __m128i)’: target specific option mismatch
 _mm_add_epi32 (__m128i __A, __m128i __B)
 ^
scrypt.cpp:329:28: error: called from here
   T = _mm_add_epi32(X2, X3);
                            ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1286:1: error: inlining failed in call to always_inline ‘__m128i _mm_xor_si128(__m128i, __m128i)’: target specific option mismatch
 _mm_xor_si128 (__m128i __A, __m128i __B)
 ^
scrypt.cpp:328:48: error: called from here
   X2 = _mm_xor_si128(X2, _mm_srli_epi32(T, 23));
                                                ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1208:1: error: inlining failed in call to always_inline ‘__m128i _mm_srli_epi32(__m128i, int)’: target specific option mismatch
 _mm_srli_epi32 (__m128i __A, int __B)
 ^
scrypt.cpp:328:21: error: called from here
   X2 = _mm_xor_si128(X2, _mm_srli_epi32(T, 23));
                     ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1286:1: error: inlining failed in call to always_inline ‘__m128i _mm_xor_si128(__m128i, __m128i)’: target specific option mismatch
 _mm_xor_si128 (__m128i __A, __m128i __B)
 ^
scrypt.cpp:327:47: error: called from here
   X2 = _mm_xor_si128(X2, _mm_slli_epi32(T, 9));
                                               ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1143:1: error: inlining failed in call to always_inline ‘__m128i _mm_slli_epi32(__m128i, int)’: target specific option mismatch
 _mm_slli_epi32 (__m128i __A, int __B)
 ^
scrypt.cpp:327:21: error: called from here
   X2 = _mm_xor_si128(X2, _mm_slli_epi32(T, 9));
                     ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1023:1: error: inlining failed in call to always_inline ‘__m128i _mm_add_epi32(__m128i, __m128i)’: target specific option mismatch
 _mm_add_epi32 (__m128i __A, __m128i __B)
 ^
scrypt.cpp:326:28: error: called from here
   T = _mm_add_epi32(X3, X0);
                            ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1286:1: error: inlining failed in call to always_inline ‘__m128i _mm_xor_si128(__m128i, __m128i)’: target specific option mismatch
 _mm_xor_si128 (__m128i __A, __m128i __B)
 ^
scrypt.cpp:325:48: error: called from here
   X3 = _mm_xor_si128(X3, _mm_srli_epi32(T, 25));
                                                ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1208:1: error: inlining failed in call to always_inline ‘__m128i _mm_srli_epi32(__m128i, int)’: target specific option mismatch
 _mm_srli_epi32 (__m128i __A, int __B)
 ^
scrypt.cpp:325:21: error: called from here
   X3 = _mm_xor_si128(X3, _mm_srli_epi32(T, 25));
                     ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1286:1: error: inlining failed in call to always_inline ‘__m128i _mm_xor_si128(__m128i, __m128i)’: target specific option mismatch
 _mm_xor_si128 (__m128i __A, __m128i __B)
 ^
scrypt.cpp:324:47: error: called from here
   X3 = _mm_xor_si128(X3, _mm_slli_epi32(T, 7));
                                               ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1143:1: error: inlining failed in call to always_inline ‘__m128i _mm_slli_epi32(__m128i, int)’: target specific option mismatch
 _mm_slli_epi32 (__m128i __A, int __B)
 ^
scrypt.cpp:324:21: error: called from here
   X3 = _mm_xor_si128(X3, _mm_slli_epi32(T, 7));
                     ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1023:1: error: inlining failed in call to always_inline ‘__m128i _mm_add_epi32(__m128i, __m128i)’: target specific option mismatch
 _mm_add_epi32 (__m128i __A, __m128i __B)
 ^
scrypt.cpp:323:28: error: called from here
   T = _mm_add_epi32(X0, X1);
                            ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1415:1: error: inlining failed in call to always_inline ‘__m128i _mm_shuffle_epi32(__m128i, int)’: target specific option mismatch
 _mm_shuffle_epi32 (__m128i __A, const int __mask)
 ^
scrypt.cpp:320:35: error: called from here
   X3 = _mm_shuffle_epi32(X3, 0x39);
                                   ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1415:1: error: inlining failed in call to always_inline ‘__m128i _mm_shuffle_epi32(__m128i, int)’: target specific option mismatch
 _mm_shuffle_epi32 (__m128i __A, const int __mask)
 ^
scrypt.cpp:319:35: error: called from here
   X2 = _mm_shuffle_epi32(X2, 0x4E);
                                   ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1415:1: error: inlining failed in call to always_inline ‘__m128i _mm_shuffle_epi32(__m128i, int)’: target specific option mismatch
 _mm_shuffle_epi32 (__m128i __A, const int __mask)
 ^
scrypt.cpp:318:35: error: called from here
   X1 = _mm_shuffle_epi32(X1, 0x93);
                                   ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1286:1: error: inlining failed in call to always_inline ‘__m128i _mm_xor_si128(__m128i, __m128i)’: target specific option mismatch
 _mm_xor_si128 (__m128i __A, __m128i __B)
 ^
scrypt.cpp:315:48: error: called from here
   X0 = _mm_xor_si128(X0, _mm_srli_epi32(T, 14));
                                                ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1208:1: error: inlining failed in call to always_inline ‘__m128i _mm_srli_epi32(__m128i, int)’: target specific option mismatch
 _mm_srli_epi32 (__m128i __A, int __B)
 ^
scrypt.cpp:315:21: error: called from here
   X0 = _mm_xor_si128(X0, _mm_srli_epi32(T, 14));
                     ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1286:1: error: inlining failed in call to always_inline ‘__m128i _mm_xor_si128(__m128i, __m128i)’: target specific option mismatch
 _mm_xor_si128 (__m128i __A, __m128i __B)
 ^
scrypt.cpp:314:48: error: called from here
   X0 = _mm_xor_si128(X0, _mm_slli_epi32(T, 18));
                                                ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1143:1: error: inlining failed in call to always_inline ‘__m128i _mm_slli_epi32(__m128i, int)’: target specific option mismatch
 _mm_slli_epi32 (__m128i __A, int __B)
 ^
scrypt.cpp:314:21: error: called from here
   X0 = _mm_xor_si128(X0, _mm_slli_epi32(T, 18));
                     ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1023:1: error: inlining failed in call to always_inline ‘__m128i _mm_add_epi32(__m128i, __m128i)’: target specific option mismatch
 _mm_add_epi32 (__m128i __A, __m128i __B)
 ^
scrypt.cpp:313:28: error: called from here
   T = _mm_add_epi32(X3, X2);
                            ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1286:1: error: inlining failed in call to always_inline ‘__m128i _mm_xor_si128(__m128i, __m128i)’: target specific option mismatch
 _mm_xor_si128 (__m128i __A, __m128i __B)
 ^
scrypt.cpp:312:48: error: called from here
   X3 = _mm_xor_si128(X3, _mm_srli_epi32(T, 19));
                                                ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1208:1: error: inlining failed in call to always_inline ‘__m128i _mm_srli_epi32(__m128i, int)’: target specific option mismatch
 _mm_srli_epi32 (__m128i __A, int __B)
 ^
scrypt.cpp:312:21: error: called from here
   X3 = _mm_xor_si128(X3, _mm_srli_epi32(T, 19));
                     ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1286:1: error: inlining failed in call to always_inline ‘__m128i _mm_xor_si128(__m128i, __m128i)’: target specific option mismatch
 _mm_xor_si128 (__m128i __A, __m128i __B)
 ^
scrypt.cpp:311:48: error: called from here
   X3 = _mm_xor_si128(X3, _mm_slli_epi32(T, 13));
                                                ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1143:1: error: inlining failed in call to always_inline ‘__m128i _mm_slli_epi32(__m128i, int)’: target specific option mismatch
 _mm_slli_epi32 (__m128i __A, int __B)
 ^
scrypt.cpp:311:21: error: called from here
   X3 = _mm_xor_si128(X3, _mm_slli_epi32(T, 13));
                     ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1023:1: error: inlining failed in call to always_inline ‘__m128i _mm_add_epi32(__m128i, __m128i)’: target specific option mismatch
 _mm_add_epi32 (__m128i __A, __m128i __B)
 ^
scrypt.cpp:310:28: error: called from here
   T = _mm_add_epi32(X2, X1);
                            ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1286:1: error: inlining failed in call to always_inline ‘__m128i _mm_xor_si128(__m128i, __m128i)’: target specific option mismatch
 _mm_xor_si128 (__m128i __A, __m128i __B)
 ^
scrypt.cpp:309:48: error: called from here
   X2 = _mm_xor_si128(X2, _mm_srli_epi32(T, 23));
                                                ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1208:1: error: inlining failed in call to always_inline ‘__m128i _mm_srli_epi32(__m128i, int)’: target specific option mismatch
 _mm_srli_epi32 (__m128i __A, int __B)
 ^
scrypt.cpp:309:21: error: called from here
   X2 = _mm_xor_si128(X2, _mm_srli_epi32(T, 23));
                     ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1286:1: error: inlining failed in call to always_inline ‘__m128i _mm_xor_si128(__m128i, __m128i)’: target specific option mismatch
 _mm_xor_si128 (__m128i __A, __m128i __B)
 ^
scrypt.cpp:308:47: error: called from here
   X2 = _mm_xor_si128(X2, _mm_slli_epi32(T, 9));
                                               ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1143:1: error: inlining failed in call to always_inline ‘__m128i _mm_slli_epi32(__m128i, int)’: target specific option mismatch
 _mm_slli_epi32 (__m128i __A, int __B)
 ^
scrypt.cpp:308:21: error: called from here
   X2 = _mm_xor_si128(X2, _mm_slli_epi32(T, 9));
                     ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1023:1: error: inlining failed in call to always_inline ‘__m128i _mm_add_epi32(__m128i, __m128i)’: target specific option mismatch
 _mm_add_epi32 (__m128i __A, __m128i __B)
 ^
scrypt.cpp:307:28: error: called from here
   T = _mm_add_epi32(X1, X0);
                            ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1286:1: error: inlining failed in call to always_inline ‘__m128i _mm_xor_si128(__m128i, __m128i)’: target specific option mismatch
 _mm_xor_si128 (__m128i __A, __m128i __B)
 ^
scrypt.cpp:306:48: error: called from here
   X1 = _mm_xor_si128(X1, _mm_srli_epi32(T, 25));
                                                ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1208:1: error: inlining failed in call to always_inline ‘__m128i _mm_srli_epi32(__m128i, int)’: target specific option mismatch
 _mm_srli_epi32 (__m128i __A, int __B)
 ^
scrypt.cpp:306:21: error: called from here
   X1 = _mm_xor_si128(X1, _mm_srli_epi32(T, 25));
                     ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1286:1: error: inlining failed in call to always_inline ‘__m128i _mm_xor_si128(__m128i, __m128i)’: target specific option mismatch
 _mm_xor_si128 (__m128i __A, __m128i __B)
 ^
scrypt.cpp:305:47: error: called from here
   X1 = _mm_xor_si128(X1, _mm_slli_epi32(T, 7));
                                               ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1143:1: error: inlining failed in call to always_inline ‘__m128i _mm_slli_epi32(__m128i, int)’: target specific option mismatch
 _mm_slli_epi32 (__m128i __A, int __B)
 ^
scrypt.cpp:305:21: error: called from here
   X1 = _mm_xor_si128(X1, _mm_slli_epi32(T, 7));
                     ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1023:1: error: inlining failed in call to always_inline ‘__m128i _mm_add_epi32(__m128i, __m128i)’: target specific option mismatch
 _mm_add_epi32 (__m128i __A, __m128i __B)
 ^
scrypt.cpp:304:28: error: called from here
   T = _mm_add_epi32(X0, X3);
                            ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1023:1: error: inlining failed in call to always_inline ‘__m128i _mm_add_epi32(__m128i, __m128i)’: target specific option mismatch
 _mm_add_epi32 (__m128i __A, __m128i __B)
 ^
scrypt.cpp:345:22: error: called from here
  B[3] = _mm_add_epi32(B[3], X3);
                      ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1023:1: error: inlining failed in call to always_inline ‘__m128i _mm_add_epi32(__m128i, __m128i)’: target specific option mismatch
 _mm_add_epi32 (__m128i __A, __m128i __B)
 ^
scrypt.cpp:344:22: error: called from here
  B[2] = _mm_add_epi32(B[2], X2);
                      ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1023:1: error: inlining failed in call to always_inline ‘__m128i _mm_add_epi32(__m128i, __m128i)’: target specific option mismatch
 _mm_add_epi32 (__m128i __A, __m128i __B)
 ^
scrypt.cpp:343:22: error: called from here
  B[1] = _mm_add_epi32(B[1], X1);
                      ^
In file included from scrypt.cpp:37:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1023:1: error: inlining failed in call to always_inline ‘__m128i _mm_add_epi32(__m128i, __m128i)’: target specific option mismatch
 _mm_add_epi32 (__m128i __A, __m128i __B)
 ^
scrypt.cpp:342:22: error: called from here
  B[0] = _mm_add_epi32(B[0], X0);
                      ^
Makefile:905: recipe for target 'scrypt.o' failed
make[3]: *** [scrypt.o] Error 1
make[3]: Leaving directory '/root/reddcoin/src'
Makefile:941: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/root/reddcoin/src'
Makefile:705: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/root/reddcoin/src'
Makefile:541: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

I already have Qtum wallet compiled and running on this machine.

**Comment by HenryYoung42** [comment]
Have you installed all development dependencies ?
Did you first run autogen.sh then configure ?

**Comment by tjosm** [comment]
Hello Henry,

Yes did installed all dependencies and ran autogen.sh. However I was building on a 32bit machine. I switched to 64bit and everything went smoothly.

**Comment by HenryYoung42** [comment]
I doubt the current version of the Reddcoin build has ever been tested on 32-bit. If you do want to investigate further I recommend searching for similar reports associated with Bitcoin 0.9, which the current version of Reddcoin Core is based on.

**Comment by reddink** [comment]
Hello @tjosm 
Reviewing your query:
Reddcoin is compatible and will compile on most 32bit architectures.
Could you advise what the device is you are attempting to compile on?

Of note from your error logs is the reference to SSE2, and I believe this is the crux of the problem
The master branch does not currently compile completely where the CPU does not have SSE2 support available (eg RaspberryPi)
In order to work on this a separate branch containing required changes is available 
https://github.com/reddcoin-project/reddcoin/tree/arm_support_v2

please take note of the build instructions located
https://github.com/reddcoin-project/reddcoin/blob/arm_support_v2/doc/build-arm.md

and specifically the --enable-sse2=no flag

please let me know if you have any issues

**Comment by TechAdeptRDD** [comment]
User hasn't responded. Issue closed.
